app:
  country: ${COUNTRY:CO}
  description: ${app.name} is a Spring Boot application
spring:
  servlet:
    multipart:
      max-file-size: 5MB
  cloud:
    loadbalancer:
      ribbon:
        enable: false
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${FAMILY_POSTGRES_HOST:localhost}:5432/${MS_NAME:BodegaX}
    username: ${MS_NAME:postgres}
    password: ${FAMILY_POSTGRES_PASSWORD:admin}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: update #change in time to none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: ${TIME_ZONE:UTC}
      org:
        hibernate:
          envers:
            default_schema: public
            store_data_at_delete: true
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-version: 0
    schemas: "public"
    locations: "classpath:db/migration"
    sql-migration-prefix: "V"
    sql-migration-suffixes: ".sql"
    baseline-on-migrate: ${BASELINE_ON_MIGRATE:true}
  jackson:
    property-naming-strategy: SNAKE_CASE
server:
  error:
    include-stacktrace: always
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
    loggers:
      enabled: true
logging:
  level:
    osia:
      com:
        examples:
          spring: TRACE
    org:
      springframework:
        cache: TRACE

